### PR TITLE
Add 'userSays' for Dialogflow Default Fallback Intent

### PR DESCRIPTION
**Pull request by digitalica**
Without some 'negative' examples, Dialogflow will show warnings in the Validation
Also, this will be a placeholder / example for adding more or changing these

See: https://community.jovo.tech/t/dialogflow-wants-negative-examples-for-the-default-fallback-intent/1203

### CODE REVIEW

**Comment by aswetlow** [comment]
Hey @digitalica 
Thank you for the contribution. To be honest, I'm not sure about it. "Cancel" and "Stop" are kind of reserved words for the `actions_intent_CANCEL` intent. (https://www.jovo.tech/tutorials/stopintent-dialogflow, https://developers.google.com/assistant/conversational/df-asdk/conversation-exits). Cancel and Stop as negative phrases don't break the StopIntent functionality but still interfer with the anticipated behavior of the CancelIntent.

A warning isn't too serious, I think. Nevertheless, It makes sense to tweak the Fallback Intent for specific use cases. Here's an example (https://cloud.google.com/dialogflow/docs/intents-default#negative-examples)

Open for feedback :)

**Comment by digitalica** [comment]
ok, i agree with your doubts about 'cancel' and 'stop', but even though warnings are not too serious, avoiding them while giving example / placeholder for improvement will help users I think. At least it would have helped me.

Maybe we can think of other / better example phrases? What do you think of something generic like:
'Go to the Dialogflow default fallback intent, not anything else'
'Please trigger the Dialogflow default fallback intent, not any other intent'

**Comment by jankoenig** [comment]
I agree with both of you. How about something like "bla" (can't think of anything else right now 😅 )

**Comment by aswetlow** [comment]
Yes, we need something that is not confusing for beginners.

Too bad that JSON does not allow comments.

**Comment by digitalica** [comment]
yeah, comments would be great in JSON, for this and many other cases.

maybe append the suggestions i gave with ' This is a negative example, as explained in dialogflow documentation'.

That is almost what i would write in documentation. chance of conflict with other intents almost 0 i think...

**Pull request closed without merging**
